[tool.isort]
profile = "black"
src_paths = ["tb3_gazebo"]
line_length = 119
# ignore files in .gitignore
skip_gitignore = true

[tool.black]
line-length = 119
target-version = ['py310']
include = '\.pyi?$'
# automatically ignore files in .gitignore
exclude = '''
(
    \.git
    | \.vscode
    | assets
    | rviz
)
'''

[tool.ruff]
line-length = 119
select = ["E", "F"]
ignore = ["E402", "E722", "F841"]
# automatically ignore files in .gitignore
exclude = [
    ".git",
    ".vscode",
    "assets",
    "rviz",
]

[tool.mypy]
python_version = 3.10
plugins = "numpy.typing.mypy_plugin"
strict = true
ignore_missing_imports = true
disallow_any_generics = false

[tool.taskipy.tasks]
fmt = "isort . && black ."
lint = "black --check . && ruff ."
mypy = "mypy ."
